const loadSupabase=()=>new Promise((resolve,reject)=>{if(window.supabase){resolve();return}const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});
(async()=>{try{await loadSupabase();const db=supabase.createClient(window.PX_SUPABASE_URL,window.PX_SUPABASE_KEY);window.pxSupabase=db;const path=location.pathname;
const log=async(event_type,metadata={})=>{const {data:{user}}=await db.auth.getUser();if(user) await db.from('activity_logs').insert({user_id:user.id,event_type,page_path:path,metadata});};
if(path.endsWith('/login.html')||path.endsWith('/register.html')){
 const form=document.querySelector('#authForm'),msg=document.querySelector('#msg'),otp=document.querySelector('#otpBox'),mode=document.body.dataset.mode;
 document.querySelector('#google')?.addEventListener('click',async()=>{const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/account.html'}});if(error)msg.textContent=error.message});
 document.querySelector('#otpSend')?.addEventListener('click',async()=>{const email=document.querySelector('#email').value.trim();if(!email)return msg.textContent='Enter your email first.';const {error}=await db.auth.signInWithOtp({email,options:{shouldCreateUser:true}});msg.textContent=error?error.message:'OTP sent. Check your email.';if(!error)otp.classList.add('show')});
 document.querySelector('#otpVerify')?.addEventListener('click',async()=>{const email=document.querySelector('#email').value.trim(),token=document.querySelector('#otp').value.trim();const {error}=await db.auth.verifyOtp({email,token,type:'email'});if(error)msg.textContent=error.message;else{await log('otp_login');location.href='account.html'}});
 form?.addEventListener('submit',async e=>{e.preventDefault();const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password')?.value; if(mode==='register'){const name=document.querySelector('#name').value.trim();const {data,error}=await db.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:location.origin+'/account.html'}});msg.textContent=error?error.message:(data.session?'Account created.':'Account created. Check your email to verify it.')}else{const {error}=await db.auth.signInWithPassword({email,password});if(error)msg.textContent=error.message;else{await log('password_login');location.href='account.html'}}});
 document.querySelector('#reset')?.addEventListener('click',async()=>{const email=document.querySelector('#email').value.trim();if(!email)return msg.textContent='Enter your email first.';const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/account.html'});msg.textContent=error?error.message:'Password reset email sent.'});
 return}
if(path.endsWith('/account.html')){const {data:{user}}=await db.auth.getUser();if(!user){location.href='login.html';return}document.querySelector('#email').textContent=user.email||'';document.querySelector('#name').value=user.user_metadata?.full_name||'';document.querySelector('#save')?.addEventListener('click',async()=>{const name=document.querySelector('#name').value.trim();const {error}=await db.auth.updateUser({data:{full_name:name}});document.querySelector('#msg').textContent=error?error.message:'Profile updated.';if(!error)await log('profile_updated')});document.querySelector('#logout').addEventListener('click',async()=>{await log('logout');await db.auth.signOut();location.href='index.html'});await log('page_view');return}
if(path.endsWith('/admin.html')){const {data:{user}}=await db.auth.getUser();if(!user){location.href='login.html';return}const {data:profile}=await db.from('profiles').select('role').eq('id',user.id).single();if(profile?.role!=='admin'){document.body.innerHTML='<main class="auth-shell"><section class="auth-card"><h1>Access denied</h1><p class="sub">This area is restricted to administrators.</p><a class="btn" href="account.html" style="display:grid;place-items:center">Back to account</a></section></main>';return}
const [{data:users},{data:logs}]=await Promise.all([db.from('profiles').select('id,email,display_name,role,created_at').order('created_at',{ascending:false}),db.from('activity_logs').select('user_id,event_type,page_path,created_at,metadata').order('created_at',{ascending:false}).limit(200)]);document.querySelector('#users').innerHTML=(users||[]).map(u=>`<tr><td>${esc(u.display_name||'—')}</td><td>${esc(u.email||'—')}</td><td>${esc(u.role)}</td><td>${new Date(u.created_at).toLocaleString()}</td></tr>`).join('');document.querySelector('#logs').innerHTML=(logs||[]).map(l=>`<tr><td>${new Date(l.created_at).toLocaleString()}</td><td>${esc(l.event_type)}</td><td>${esc(l.page_path||'')}</td><td>${esc((users||[]).find(u=>u.id===l.user_id)?.email||'—')}</td></tr>`).join('');document.querySelector('#userCount').textContent=(users||[]).length;document.querySelector('#logCount').textContent=(logs||[]).length;return}
}catch(e){console.error(e)}})();
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}