document.addEventListener('DOMContentLoaded',()=>{
const nav=document.querySelector('.nav'),progress=document.querySelector('.progress');
const commands=[
['Home','index.html','G H'],['Projects','projects.html','G P'],['Number Lookup','number-lookup.html','G N'],
['About','about.html','G A'],['Services','services.html','G S'],['Roadmap','roadmap.html','G R'],['Contact','contact.html','G C'],
['Email','mailto:princeraj74682@gmail.com',''],['Instagram','https://www.instagram.com/princeraj0205/','']
];
function scrollUI(){if(nav)nav.classList.toggle('scrolled',scrollY>20);if(progress){let h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h?scrollY/h*100:0)+'%'}}scrollUI();addEventListener('scroll',scrollUI,{passive:true});
document.querySelectorAll('.reveal').forEach(x=>new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.1}).observe(x));
let overlay=document.createElement('div');overlay.className='cmd-backdrop';overlay.innerHTML='<div class="cmd" role="dialog" aria-label="Command palette"><input aria-label="Search commands" placeholder="Search pages, actions..." autocomplete="off"><div class="cmdlist"></div></div>';document.body.appendChild(overlay);
let input=overlay.querySelector('input'),list=overlay.querySelector('.cmdlist'),sel=0;
function render(q=''){let arr=commands.filter(c=>c[0].toLowerCase().includes(q.toLowerCase()));list.innerHTML=arr.map((c,i)=>`<div class="cmditem ${i===sel?'sel':''}" data-i="${i}"><span>${c[0]}</span><kbd>${c[2]}</kbd></div>`).join('');list.querySelectorAll('.cmditem').forEach((e,i)=>e.onclick=()=>{let a=arr[i][1];if(a.startsWith('http'))window.open(a,'_blank');else location.href=a})}
function openCmd(){overlay.classList.add('open');input.value='';sel=0;render();setTimeout(()=>input.focus(),30)}function closeCmd(){overlay.classList.remove('open')}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCmd()}if(e.key==='Escape')closeCmd();if(overlay.classList.contains('open')){let items=list.children;if(e.key==='ArrowDown'){e.preventDefault();sel=Math.min(sel+1,items.length-1);render(input.value)}if(e.key==='ArrowUp'){e.preventDefault();sel=Math.max(sel-1,0);render(input.value)}if(e.key==='Enter'&&items[sel])items[sel].click()}});
input.addEventListener('input',()=>{sel=0;render(input.value)});overlay.addEventListener('click',e=>{if(e.target===overlay)closeCmd()});
let g=false;document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='g'){g=true;setTimeout(()=>g=false,900);return}if(g){let m={h:'index.html',p:'projects.html',n:'number-lookup.html',a:'about.html',s:'services.html',r:'roadmap.html',c:'contact.html'}[e.key.toLowerCase()];if(m)location.href=m;g=false}});
const dot=document.createElement('div'),ring=document.createElement('div');dot.className='cursor-dot';ring.className='cursor-ring';document.body.append(dot,ring);if(matchMedia('(pointer:fine)').matches){dot.style.display=ring.style.display='block';let mx=0,my=0,rx=0,ry=0;addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;dot.style.left=mx-3+'px';dot.style.top=my-3+'px'});(function loop(){rx+=(mx-rx)*.18;ry+=(my-ry)*.18;ring.style.left=rx-15+'px';ring.style.top=ry-15+'px';requestAnimationFrame(loop)})()}
document.querySelectorAll('.magnetic').forEach(el=>el.addEventListener('mousemove',e=>{let r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.08}px)`}).addEventListener('mouseleave',()=>el.style.transform=''));
document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);toast('Copied')}catch{}}));
function toast(t){let x=document.querySelector('.toast');if(!x){x=document.createElement('div');x.className='toast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1300)}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');let f=btn.dataset.filter;document.querySelectorAll('.filter-item').forEach(x=>x.classList.toggle('hide',f!=='all'&&!x.dataset.type.split(' ').includes(f)))}));
});